SharpTheory/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SharpTheory.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

SharpTheory/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SharpTheory.Models;
using SharpTheory.Services;
using System.Text;
using System.Text.Json;

namespace SharpTheory.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IAnalyticsService _analyticsService;
        private readonly TheoryDataService _dataService;
        public DateTime CurrentTime { get; set; }
        public TheoryDescription? Description { get; set; }

        public IndexModel(ILogger<IndexModel> logger, IAnalyticsService analyticsService, TheoryDataService dataService)
        {
            _logger = logger;
            _analyticsService = analyticsService;
            _dataService = dataService;
        }

        public void OnGet()
        {
            var root = _dataService.Root;
            Description = root?.Description;

            CurrentTime = DateTime.Now;

            _logger.LogInformation("Index page loaded at {Time}", CurrentTime);
            _ = _analyticsService.SendEventAsync("IndexPageView");
        }

    }
}

SharpTheory/Pages/KeyQuiz.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SharpTheory.Models;
using SharpTheory.Services;
using System.Text.Json;

namespace SharpTheory.Pages
{
    /// <summary>
    /// PageModel for the Key Quiz page, handles quiz logic and user interactions.
    /// </summary>
    public class KeyQuizModel : PageModel
    {
        private readonly ILogger<KeyQuizModel> _logger;
        private readonly IAnalyticsService _analyticsService;
        private readonly TheoryDataService _dataService;

        public KeyQuizModel(ILogger<KeyQuizModel> logger, IAnalyticsService analyticsService, TheoryDataService dataService)
        {
            _logger = logger;
            _analyticsService = analyticsService;
            _dataService = dataService;
        }

        /// <summary>
        /// Pool of keys to select from, filtered based on user preferences.
        /// </summary>
        private List<TheoryKey>? KeyPool { get; set; }
        /// <summary>
        /// The currently selected key for the quiz.
        /// </summary>
        public TheoryKey? Key { get; set; }
        /// <summary>
        /// Gets or sets the number of sharps for the selected key.
        /// </summary>
        public int? NumSharps { get; set; }
        /// <summary>
        /// Gets or sets the number of flats for the selected key.
        /// </summary>
        public int? NumFlats { get; set; }

        /// <summary>
        /// Gets or sets the name of the selected key. This is bound to a hidden input to maintain state across requests.
        /// </summary>
        [BindProperty]
        public string? SelectedKeyName { get; set; }

        // User inputs
        /// <summary>
        /// Gets or sets the number of sharps input by the user.
        /// </summary>
        [BindProperty]
        public int? UserSharps { get; set; }

        /// <summary>
        /// Gets or sets the number of flats input by the user.
        /// </summary>
        [BindProperty]
        public int? UserFlats { get; set; }

        /// <summary>
        /// Gets or sets the result message to be displayed after user submission.
        /// </summary>
        public string? ResultMessage { get; set; }


        /// <summary>
        /// Gets or sets sharps only flag for KeyPool.
        /// </summary>
        [BindProperty(SupportsGet = true)]
        public bool OnlySharps { get; set; } = false;

        /// <summary>
        /// Gets or sets flats only flag for KeyPool.
        /// </summary>
        [BindProperty(SupportsGet = true)]
        public bool OnlyFlats { get; set; } = false;


        /// <summary>
        /// Gets or sets the count of correct answers, stored in session.
        /// </summary>
        public int RightCount
        {
            get => HttpContext.Session.GetInt32("RightCount") ?? 0;
            set => HttpContext.Session.SetInt32("RightCount", value);
        }

        /// <summary>
        /// Gets or sets the count of incorrect answers, stored in session.
        /// </summary>
        public int WrongCount
        {
            get => HttpContext.Session.GetInt32("WrongCount") ?? 0;
            set => HttpContext.Session.SetInt32("WrongCount", value);
        }

        /// <summary>
        /// Handles GET requests by selecting a random key to be rendered
        /// </summary>
        /// <remarks>
        /// First, OnGet() checks querystring for flags and sets flags accordingly. Then it reads data.json 
        /// sets KeyPool according to flags. Finally, it selects a random key and assigns it.
        /// </remarks>
        public void OnGet()
        {
            if (!Request.Query.ContainsKey("OnlySharps"))
            {
                OnlySharps = HttpContext.Session.GetInt32("OnlySharps") == 1;
                OnlyFlats = HttpContext.Session.GetInt32("OnlyFlats") == 1;
            }
            else
            {
                HttpContext.Session.SetInt32("OnlySharps", OnlySharps ? 1 : 0);
                HttpContext.Session.SetInt32("OnlyFlats", OnlyFlats ? 1 : 0);
            }

            var root = _dataService.Root;
            if (OnlySharps)
            {
                KeyPool = root?.Keys.Where(k => k.NumSharps > 0).ToList();
            }
            else if (OnlyFlats)
            {
                KeyPool = root?.Keys.Where(k => k.NumFlats > 0).ToList();
            }
            else
            {
                KeyPool = root?.Keys;
            }

            var random = new Random();
            if (KeyPool != null)
            {
                Key = KeyPool[random.Next(KeyPool.Count)];
                NumSharps = Key?.NumSharps;
                NumFlats = Key?.NumFlats;
                SelectedKeyName = Key?.Name;
            }
            _logger.LogInformation("KeyQuiz page loaded at {Time}", DateTime.Now);
            _analyticsService.SendEventAsync("KeyQuizPageView");
        }

        /// <summary>
        /// Handles POST requests by validating user's submitted key and updating ResultMessage
        /// </summary>
        /// <remarks>
        /// Reads data.json and ensures that Key is set correctly.SelectedKey is bound to a hidden input 
        /// on KeyQuiz.cshtml that ensures persistence. UserSharps/UserFlats default to 0. Result message is
        /// set accordingly.
        /// </remarks>
        public void OnPost()
        {
            var root = _dataService.Root;

            if (root != null && !string.IsNullOrEmpty(SelectedKeyName))
            {
                Key = root.Keys.FirstOrDefault(k => k.Name == SelectedKeyName);
                NumSharps = Key?.NumSharps ?? 0;
                NumFlats = Key?.NumFlats ?? 0;
            }

            UserSharps ??= 0;
            UserFlats ??= 0;

            if (UserSharps == NumSharps && UserFlats == NumFlats)
            {
                ResultMessage = $"Correct! {NumSharps} Sharps and {NumFlats} Flats";
                RightCount++;
            }
            else
            {
                ResultMessage = $"Incorrect. The correct answer is {NumSharps} sharps and {NumFlats} flats.";
                WrongCount++;
            }
            _logger.LogInformation("KeyQuiz post request loaded at {Time}", DateTime.Now);
            _analyticsService.SendEventAsync("Post");
        }

        /// <summary>
        /// Refreshes page for a new question
        /// </summary>
        /// /// <returns>An <see cref="IActionResult"/> that redirects to the current page.</returns>
        public IActionResult OnPostNewQuestion()
        {
            return RedirectToPage();
        }

        /// <summary>
        /// Resets the counters for correct and incorrect answers to zero and redirects to the current page.
        /// </summary>
        /// <returns>An <see cref="IActionResult"/> that redirects to the current page.</returns>
        public IActionResult OnPostClear()
        {
            RightCount = 0;
            WrongCount = 0;
            return RedirectToPage();
        }
    }
}

SharpTheory/Pages/KeyReference.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SharpTheory.Models;
using System.Text.Json;
using SharpTheory.Services;

namespace SharpTheory.Pages
{
    /// <summary>
    /// PageModel for the Key Reference page, loads and displays key signatures and descriptions.
    /// </summary>
    public class KeyReferenceModel : PageModel
    {
        private readonly ILogger<KeyReferenceModel> _logger;
        private readonly IAnalyticsService _analyticsService;
        private readonly TheoryDataService _dataService;
        public KeyReferenceModel(ILogger<KeyReferenceModel> logger, IAnalyticsService analyticsService, TheoryDataService dataService)
        {
            _logger = logger;
            _analyticsService = analyticsService;
            _dataService = dataService;
        }
        /// <summary>
        /// Description of API
        /// </summary>
        public TheoryDescription? Description { get; set; }

        /// <summary>
        /// List of all keys from data.json
        /// </summary>
        public List<TheoryKey>? Keys { get; set; }

        /// <summary>
        /// Handles GET requests to load key data from JSON file.
        /// </summary>
        public void OnGet()
        {
            _logger.LogInformation("KeyReference page loaded");
            _ = _analyticsService.SendEventAsync("PageView");
            var root = _dataService.Root;
            Description = root?.Description;
            Keys = root?.Keys;
        }
    }
}

SharpTheory/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SharpTheory.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

SharpTheory/Pages/Register.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SharpTheory.Pages;

public class Register : PageModel
{
    private readonly ILogger<Register> _logger;
    private readonly IConfiguration _config;
    private readonly HttpClient _client;

    public Register(ILogger<Register> logger ,IConfiguration config, IHttpClientFactory clientFactory)
    {
        _logger = logger;
        _config = config;
        _client = clientFactory.CreateClient("Default");
    }
    
    [BindProperty]
    public InputModel Input { get; set; }

    public class InputModel
    {
        [Required]
        public string Name { get; set; }
        
        [Required, EmailAddress]
        public string Email { get; set; }
        
        [Required, DataType(DataType.Password)]
        public string Password { get; set; }
        
        [Required]
        public DateTime Birthday { get; set; }
        
    }
    
    public void OnGet()
    {
        
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
        {
            _logger.LogError("Invalid input");
            return Page();
        }

        var baseUrl = _config["Microservice:BaseUrl"];
        var url = $"{baseUrl}/api/profile";

        var json = JsonSerializer.Serialize(Input);
        var content = new StringContent(json, Encoding.UTF8, "application/json");
        
        var response = await _client.PostAsync(url, content);
        
        if (!response.IsSuccessStatusCode)
        {
            _logger.LogError("Server returned error");
            ModelState.AddModelError(string.Empty, "Registration failed.");
            return Page();
        }
        
        _logger.LogInformation("Registration succeeded");
        return RedirectToPage("/Index");
    }
}

SharpTheory/Pages/ScaleQuiz.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SharpTheory.Models;
using SharpTheory.Services;
using System.Text.Json;

namespace SharpTheory.Pages
{
    public class ScaleQuizModel : PageModel
    {
        private readonly ILogger<ScaleQuizModel> _logger;
        private readonly IAnalyticsService _analyticsService;
        public List<TheoryInteger>? Integers { get; set; }
        public List<int> RawInts { get; set; } = [];
        public TheoryScale? Scale { get; set; }
        public bool ShowNotes { get; set; } = true;
        [BindProperty]
        public int ScaleInt { get; set; } = 0;

        public ScaleQuizModel(ILogger<ScaleQuizModel> logger, IAnalyticsService analyticsService)
        {
            _logger = logger;
            _analyticsService = analyticsService;
        }
        public void OnGet()
        {
            _logger.LogInformation("ScaleQuiz OnGet called.");
            var json = System.IO.File.ReadAllText("Data/data.json");
            var root = JsonSerializer.Deserialize<TheoryRoot>(json);
            if (root == null)
            {
                return;
            }
            Integers = root.Integers.ToList();

            var majorScales = root.Scales.Where(s => s.Major != null).ToList();
            Scale = majorScales[0];
            if (Scale != null && Scale.Major != null)
            {
                foreach (var i in Scale.Major.Integers)
                {
                    RawInts.Add(i);
                }
            }
            _logger.LogInformation("ScaleQuiz page loaded at {Time}", DateTime.Now);
            _analyticsService.SendEventAsync("PageView");
        }

        public void OnPost()
        {
            _logger.LogInformation("ScaleQuiz OnPost called.");
            var json = System.IO.File.ReadAllText("Data/data.json");
            var root = JsonSerializer.Deserialize<TheoryRoot>(json);
            if (root == null)
            {
                return;
            }
            Integers = root.Integers.ToList();

            var majorScales = root.Scales.Where(s => s.Major != null).ToList();
            _logger.LogInformation($"ScaleInt = {ScaleInt}");
            Scale = majorScales.FirstOrDefault(s => s.Integer.Equals(ScaleInt));

            if (Scale != null && Scale.Major != null)
            {
                foreach (var i in Scale.Major.Integers)
                {
                    RawInts.Add(i);
                }
            }
            _logger.LogInformation("ScaleQuiz page loaded at {Time}", DateTime.Now);
            _analyticsService.SendEventAsync("PageView");
        }
    }
}

SharpTheory/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<div class="staff-background">
    @if (Model.Description != null)
    {
        <div class="text-center">
            <h2>@Model.Description.Title</h2>
            <p>@Model.Description.Description</p>
            <p>Author: @Model.Description.Author</p>
        </div>
    } 

    <div class="text-center">
        <p>
            SharpTheory is a Music Theory website/API written in C# (hence the name!). 
            This project is both a chance for me to learn C# for web development and to provide a potentially 
            useful public API.  
        </p>
        <p>
            The full source code for this site is available on 
            <a class="plain-link" href="https://github.com/mmnessim/SharpTheoryRazorPages" target="_blank">
                Github. 
            </a>
            Additionally, the JSON file containing the raw music theory data is available in its own 
            <a class="plain-link" href="https://github.com/mmnessim/music_theory_json" target="_blank">
                repository.
            </a>
            This project is still a bit of a work in progress, so feel free to contact me if you encounter any bugs or issues
        </p>
        <div>
            <h2>
                <a class="plain-link" asp-area="" asp-page="/KeyQuiz">
                    Key Quiz
                </a>
            </h2>
            <p>
                One possible use of this API is to create quizzes or other practice content. The Key Quiz page is a simple
                quiz in which you enter the number of sharps or flats in the given key. 
            </p>
            <h2>
                <a class="plain-link" asp-area="" asp-page="/KeyReference">
                    Key Reference    
                </a>
            </h2>
            <p>
                The API could also be used to generate and display various information about diatonic keys.     
            </p>
        </div>
        <!--
            <div>
                <h3>Todos:</h3>
                <ol>
                    <li>Sort out Swagger/OpenAPI Documentation</li>
                    <li>Implement a Scales quiz?</li>
                    <li>Intervals quiz?</li>
                    <li>Terms of use for the API</li>
                    <li>Tests!</li>
                </ol>
            </div>
        -->
    </div>
</div>

SharpTheory/Pages/KeyQuiz.cshtml
@page "/quiz" 
@model SharpTheory.Pages.KeyQuizModel

<div class="staff-background">
    @if (Model.Key != null && Model.NumSharps != null)
    {
        <div class="d-flex gap-2 mb-3">
            <form method="get" asp-page-handler="">
                <input type="hidden" name="OnlySharps" value="true" />
                <input type="hidden" name="OnlyFlats" value="false" />
                <button type="submit"
                        class="btn btn-primary @(Model.OnlySharps && !Model.OnlyFlats ? "btn-active" : "")">
                    Sharps Only
                </button>
            </form>
            <form method="get" asp-page-handler="">
                <input type="hidden" name="OnlySharps" value="false" />
                <input type="hidden" name="OnlyFlats" value="true" />
                <button type="submit"
                        class="btn btn-primary @(Model.OnlyFlats && !Model.OnlySharps ? "btn-active" : "")">
                    Flats Only
                </button>
            </form>
            <form method="get" asp-page-handler="">
                <input type="hidden" name="OnlySharps" value="false" />
                <input type="hidden" name="OnlyFlats" value="false" />
                <button type="submit" class="btn btn-primary @(!Model.OnlySharps && !Model.OnlyFlats ? "btn-active" : "")">All Keys</button>
            </form>
        </div>
        @if (Model.RightCount != 0 || Model.WrongCount != 0)
        {
            <div class="d-flex gap-2 align-items-center">
                <h4>@(Model.RightCount)/@(Model.RightCount + Model.WrongCount) Correct answers</h4>
                <form method="post" asp-page-handler="Clear">
                    <button type="submit" class="btn btn-danger mt-2">Clear Score</button>
                </form>
            </div>

        }

        <h1>How many sharps or flats does @Model.Key.Name have?</h1>
        <form method="post">
            <input type="hidden" asp-for="SelectedKeyName" />
            <div class="mb-2">
                <label asp-for="UserSharps" class="form-label">Sharps</label>
                <input type="number" asp-for="UserSharps" class="form-control" />
            </div>
            <div class="mb-2">
                <label asp-for="UserFlats" class="form-label">Flats</label>
                <input type="number" asp-for="UserFlats" class="form-control" />
            </div>
            @if (Model.ResultMessage == null)
            {
                <button type="submit" class="btn btn-primary mt-2">Submit</button>
            }
        </form>

        <form method="post" asp-page-handler="NewQuestion">
            <button type="submit" class="btn btn-secondary mt-2">New Question</button>
        </form>

        @if (Model.ResultMessage != null)
        {
            <div class="mt-3">@Model.ResultMessage</div>
        }
    }
</div>

SharpTheory/Pages/KeyReference.cshtml
@page "/KeyReference"
@model SharpTheory.Pages.KeyReferenceModel

<div class="staff-background">
    <h1>Key Reference</h1>
    <p>
        Click on any key to get some basic information about it.
    </p>

    @if (Model.Keys is { Count: > 0 })
    {
        @await Html.PartialAsync("Partials/_KeyListPartial", Model.Keys)
    }
    
</div>

SharpTheory/Pages/Register.cshtml
@page "/Register"
@model SharpTheory.Pages.Register
    
<div>
    <h1>Register a new User</h1>
    <form method="post">
        <div>
            <label asp-for="Input.Name"></label>
            <input asp-for="Input.Name" />
            <span asp-validation-for="Input.Name"></span>
        </div>
        <div>
            <label asp-for="Input.Email"></label>
            <input asp-for="Input.Email" type="email" />
            <span asp-validation-for="Input.Email"></span>
        </div>
        <div>
            <label asp-for="Input.Password"></label>
            <input asp-for="Input.Password" type="password" />
            <span asp-validation-for="Input.Password"></span>
        </div>
        <div>
            <label asp-for="Input.Birthday"></label>
            <input asp-for="Input.Birthday" type="date" />
            <span asp-validation-for="Input.Birthday"></span>
        </div>
        <button type="submit">Register</button>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

SharpTheory/Pages/ScaleQuiz.cshtml
@page "/scalevisualizer"
@model SharpTheory.Pages.ScaleQuizModel
<h1>
    Scale Visualizer
</h1>
@{
    var whiteKeyNotes = new[] { 0, 2, 4, 5, 7, 9, 11 };
    var blackKeyOffsets = new Dictionary<int, int>
{
{ 1, 35 },
{ 3, 85 },
{ 6, 185 },
{ 8, 235 },
{ 10, 285 }
};
}

@if (Model.Integers != null && Model.Scale != null)
{
    <div class="d-flex">
        <div class="piano">
            @foreach (var note in whiteKeyNotes)
            {
                <div class="white-key 
                            @(Model.RawInts.Contains(note) ? "included-in-key" : "")
                            @(Model.RawInts[0] == note ? "tonic-key" : "")
                            @* @(Model.RawInts[4] == note ? "dominant-key" : "")      *@
                                " data-note="@note">
                    @Model.Integers?.FirstOrDefault(i => i.Integer == note)?.Names[0]
                </div>
            }
            @foreach (var note in whiteKeyNotes)
            {
                <div class="white-key
                            @(Model.RawInts.Contains(note) ? "included-in-key" : "")
                            @(Model.RawInts[0] == note ? "tonic-key" : "")
                            @* @(Model.RawInts[4] == note ? "dominant-key" : "") *@
                                " data-note="@note">
                    @Model.Integers?.FirstOrDefault(i => i.Integer == note)?.Names[0]
                </div>
            }
            <div class="black-keys">
                @foreach (var kvp in blackKeyOffsets)
                {
                    <div class="black-key 
                                @(Model.RawInts.Contains(kvp.Key) ? "included-in-key" : "")
                                @(Model.RawInts[0] == kvp.Key ? "tonic-key" : "")
                                @* @(Model.RawInts[4] == kvp.Key ? "dominant-key" : "") *@
                                " style="left: @($"{kvp.Value}px");" data-note="@kvp.Key">
                        @Model.Integers?.FirstOrDefault(i => i.Integer == kvp.Key)?.Names[0] /
                        @Model.Integers?.FirstOrDefault(i => i.Integer == kvp.Key)?.Names[1]
                    </div>
                }
                @foreach (var kvp in blackKeyOffsets)
                {
                    <div class="black-key
                                @(Model.RawInts.Contains(kvp.Key) ? "included-in-key" : "")
                                @(Model.RawInts[0] == kvp.Key ? "tonic-key" : "")
                                @* @(Model.RawInts[4] == kvp.Key ? "dominant-key" : "") *@
                                " style="left: @($"{kvp.Value + 335}px");" data-note="@kvp.Key">
                        @Model.Integers?.FirstOrDefault(i => i.Integer == kvp.Key)?.Names[0] /
                        @Model.Integers?.FirstOrDefault(i => i.Integer == kvp.Key)?.Names[1]
                    </div>
                }
            </div>
        </div>
    </div>

    <div class="scale-container d-flex">
        @foreach (var I in Model.Integers)
        {
            <form method="post">
                <input type="hidden" asp-for="ScaleInt" value="@I.Integer" />
                <button class="btn btn-secondary m-1
                    @(I.Integer == Model.Scale.Integer ? "included" : "")
                    @(Model.Scale.Major != null &&
                    (
                        Model.Scale.Major.Notes.Contains(I.Names[0]) ||
                        (I.Names.Count > 1 && Model.Scale.Major.Notes.Contains(I.Names[1]))
                        )
                        ? "selected" : "")">
                        @I.Names[0]@(I.Names.Count > 1 ? " / " + I.Names[1] : "")
                 </button>
            </form>
        }
    </div>
}

SharpTheory/Pages/ScaleVisualizer.cshtml
@page "/scalevisualizer"
@model SharpTheory.Pages.ScaleQuizModel
<h1>
    Major Scale Visualizer
</h1>
@if (Model.Scale != null)
{
    <h2>@Model.Scale.Tonic Major </h2>
}
@{
    var whiteKeyNotes = new[] { 0, 2, 4, 5, 7, 9, 11 };
    var blackKeyOffsets = new Dictionary<int, int>
{
{ 1, 35 },
{ 3, 85 },
{ 6, 185 },
{ 8, 235 },
{ 10, 285 }
};
}

@if (Model.Integers != null && Model.Scale != null)
{
    <div class="d-flex">
        <div class="piano">
            @foreach (var note in whiteKeyNotes)
            {
                <div class="white-key 
                            @(Model.RawInts.Contains(note) ? "included-in-key" : "")
                            @(Model.RawInts[0] == note ? "tonic-key" : "")
                                " data-note="@note">
                    @Model.Integers?.FirstOrDefault(i => i.Integer == note)?.Names[0]
                </div>
            }
            @foreach (var note in whiteKeyNotes)
            {
                <div class="white-key
                            @(Model.RawInts.Contains(note) ? "included-in-key" : "")
                            @(Model.RawInts[0] == note ? "tonic-key" : "")
                                " data-note="@note">
                    @Model.Integers?.FirstOrDefault(i => i.Integer == note)?.Names[0]
                </div>
            }
            <div class="black-keys">
                @foreach (var kvp in blackKeyOffsets)
                {
                    <div class="black-key 
                                @(Model.RawInts.Contains(kvp.Key) ? "included-in-key" : "")
                                @(Model.RawInts[0] == kvp.Key ? "tonic-key" : "")
                                " style="left: @($"{kvp.Value}px");" data-note="@kvp.Key">
                        @Model.Integers?.FirstOrDefault(i => i.Integer == kvp.Key)?.Names[0] /
                        @Model.Integers?.FirstOrDefault(i => i.Integer == kvp.Key)?.Names[1]
                    </div>
                }
                @foreach (var kvp in blackKeyOffsets)
                {
                    <div class="black-key
                                @(Model.RawInts.Contains(kvp.Key) ? "included-in-key" : "")
                                @(Model.RawInts[0] == kvp.Key ? "tonic-key" : "")
                                " style="left: @($"{kvp.Value + 335}px");" data-note="@kvp.Key">
                        @Model.Integers?.FirstOrDefault(i => i.Integer == kvp.Key)?.Names[0] /
                        @Model.Integers?.FirstOrDefault(i => i.Integer == kvp.Key)?.Names[1]
                    </div>
                }
            </div>
        </div>
    </div>

    <div class="scale-container d-flex">
        @foreach (var I in Model.Integers)
        {
            <form method="post">
                <input type="hidden" asp-for="ScaleInt" value="@I.Integer" />
                <button class="btn btn-secondary m-1
                    @(I.Integer == Model.Scale.Integer ? "included" : "")
                    ">
                        @I.Names[0]@(I.Names.Count > 1 ? " / " + I.Names[1] : "")
                 </button>
            </form>
        }
    </div>
}